# Ensure this version tracks with go.mod and /Dockerfile
FROM golang:1.19

RUN apt-get update && apt-get install -y awscli

WORKDIR /src
COPY ./ /src
RUN go get ./...

CMD ["go", "test", "-v", "./..."]
